name: my-finroc-snaptest-app
version: 1
summary: my-finroc-snaptest-app summary
description: my-finroc-snaptest-app description

#"confinement" property not specified: defaulting to "strict"
#"grade" property not specified: defaulting to "stable"
#grade: devel # stable is default
#confinement: devmode # strict is default

parts:
  part-name:
    source: /home/arasdar/finroc/export/linux_x86_64_debug/bin/
    plugin: dump

apps:
  app-name:
    command: finroc_crash_course
    plugs: [network-bind] # server and the client is just network